"""Inline the vLLM serving-profile block into the Duck submission notebook.

Same single-source-of-truth pattern as `_patch_duck_notebook_budget.py`: a
Kaggle kernel has no import path back into this repo, so the notebook must
carry its own copy of the logic -- and that copy is *generated* from
`kaggle_submission_duck/vllm_serving.py` rather than hand-typed twice, so the
two cannot drift apart silently. `tests/test_duck_notebook_serving.py` asserts
the notebook's inlined block still matches what this script would emit.

What it injects (cell 5, inside the existing `_patch_qwen38_setup_commands`):

  * `DUCK_VLLM_SERVING_PROFILE` -- one named constant selecting the profile.
    Defaults to `"baseline"`, which is an exact no-op: an unmeasured profile
    must never ship as the default.
  * a per-profile source patch applied to the bundle's setup here-doc, inserted
    immediately before the line that launches the vLLM server.
  * a substitution-count check that raises if the anchor was not found exactly
    once -- matching the contract the surrounding `_patch_qwen38_setup_commands`
    already uses for the model-identity replacements. A silently-unpatched
    command would launch the baseline server while the notebook claimed
    otherwise, which is precisely the class of silent failure this repo has
    been burned by before.

Usage (from repo root):
    python scripts/_patch_duck_notebook_serving.py [--profile NAME] [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from kaggle_submission_duck.vllm_serving import (  # noqa: E402
    BASELINE_PROFILE,
    LAUNCH_ANCHOR,
    PROFILES,
    build_setup_patch,
)

NOTEBOOK = (
    REPO_ROOT
    / "kaggle_submission_duck"
    / "notebook"
    / "lb-9-arc3-duck-v12-with-qwen-3-8-27b.ipynb"
)

BEGIN = "# --- BEGIN stage7-duck-throughput serving profile (generated) ---"
END = "# --- END stage7-duck-throughput serving profile (generated) ---"

# Where the block is inserted, and where it is applied, in cell 5.
CONSTANTS_ANCHOR = "def _patch_qwen38_setup_commands(commands: list[str]) -> list[str]:"
APPLY_ANCHOR = "        patched.append(command)"
VERIFY_ANCHOR = "    missing = ["


def render_block(profile: str) -> str:
    """The generated source that gets inlined into the notebook."""
    if profile not in PROFILES:
        raise KeyError(f"unknown serving profile {profile!r}; known: {sorted(PROFILES)}")
    patches = {
        name: build_setup_patch(name)
        for name in sorted(PROFILES)
        if name != BASELINE_PROFILE
    }
    lines = [
        BEGIN,
        "# Generated by scripts/_patch_duck_notebook_serving.py from",
        "# kaggle_submission_duck/vllm_serving.py -- do not hand-edit.",
        "#",
        "# The public fork this is derived from sets TAAF_VLLM_* environment",
        "# variables, which are read ONLY by that fork's own source bundle. Our",
        "# bundle contains zero references to them, so setting them here would be a",
        "# silent no-op. We patch the real vLLM argv instead. See",
        "# experiments/stage7_duck_throughput.md for the measurements behind the",
        "# selected profile.",
        f"DUCK_VLLM_SERVING_PROFILE = {profile!r}",
        f"DUCK_VLLM_LAUNCH_ANCHOR = {LAUNCH_ANCHOR!r}",
        "DUCK_VLLM_PROFILE_PATCHES = {",
    ]
    for name, patch in patches.items():
        lines.append(f"    {name!r}: {patch!r},")
    lines += [
        "}",
        "",
        "",
        "def _duck_apply_serving_profile(command: str) -> tuple[str, int]:",
        '    """Insert the serving-profile argv patch before the vLLM launch line."""',
        f"    if DUCK_VLLM_SERVING_PROFILE == {BASELINE_PROFILE!r}:",
        "        return command, 0",
        "    patch = DUCK_VLLM_PROFILE_PATCHES[DUCK_VLLM_SERVING_PROFILE]",
        "    if DUCK_VLLM_LAUNCH_ANCHOR not in command:",
        "        return command, 0",
        "    return (",
        '        command.replace(DUCK_VLLM_LAUNCH_ANCHOR, patch + "\\n" + DUCK_VLLM_LAUNCH_ANCHOR, 1),',
        "        1,",
        "    )",
        END,
    ]
    return "\n".join(lines) + "\n\n\n"


APPLY_SNIPPET = """\
        # stage7-duck-throughput: apply the vLLM serving profile (no-op on
        # 'baseline'). Counted so an unmatched anchor is a hard error below
        # rather than a server that silently launches with the old argv.
        command, _serving_count = _duck_apply_serving_profile(command)
        serving_patch_count += _serving_count

"""

VERIFY_SNIPPET = """\
    if DUCK_VLLM_SERVING_PROFILE != {baseline!r} and serving_patch_count != 1:
        raise RuntimeError(
            "Could not apply the vLLM serving profile "
            f"{{DUCK_VLLM_SERVING_PROFILE!r}}: expected exactly 1 patched setup "
            f"command, patched {{serving_patch_count}}. The attached TAAF "
            "bundle's vLLM launch line has changed."
        )
    print(
        "taaf.kaggle: vLLM serving profile =",
        DUCK_VLLM_SERVING_PROFILE,
        f"(patched {{serving_patch_count}} setup command(s))",
        flush=True,
    )

""".format(baseline=BASELINE_PROFILE)


def strip_existing(source: str) -> str:
    """Remove a previously-generated block so the patch is idempotent."""
    if BEGIN not in source:
        return source
    head, rest = source.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + tail.lstrip("\n")


def patch_cell(source: str, profile: str) -> str:
    """Apply (or re-apply) the serving block. Idempotent.

    Idempotency is load-bearing, not a nicety: `--check` compares
    `patch_cell(committed) == committed`, and switching profiles means running
    this over an already-patched notebook. Only the generated BEGIN/END block
    is stripped and rewritten; the three call-site insertions are guarded by
    their own markers, because blindly re-inserting them duplicated
    `serving_patch_count` and the verification (caught by
    tests/test_duck_notebook_serving.py).
    """
    source = strip_existing(source)
    for anchor in (CONSTANTS_ANCHOR, APPLY_ANCHOR, VERIFY_ANCHOR):
        if anchor not in source:
            raise RuntimeError(f"cell 5 anchor not found: {anchor!r}")

    # 1. constants + helper, immediately above the existing patch function
    source = source.replace(CONSTANTS_ANCHOR, render_block(profile) + CONSTANTS_ANCHOR, 1)
    # 2. a counter initialised alongside the existing replacement_counts
    if "serving_patch_count = 0" not in source:
        source = source.replace(
            "    patched: list[str] = []\n",
            "    patched: list[str] = []\n    serving_patch_count = 0\n",
            1,
        )
    # 3. apply inside the per-command loop, before the command is kept
    if "_duck_apply_serving_profile(command)" not in source:
        source = source.replace(APPLY_ANCHOR, APPLY_SNIPPET + APPLY_ANCHOR, 1)
    # 4. verify after the loop, alongside the existing missing-assignment check
    if "serving_patch_count != 1" not in source:
        source = source.replace(VERIFY_ANCHOR, VERIFY_SNIPPET + VERIFY_ANCHOR, 1)
    return source


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", default=BASELINE_PROFILE, choices=sorted(PROFILES))
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the notebook is not already up to date")
    args = parser.parse_args()

    nb = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    cell = nb["cells"][5]
    if cell["cell_type"] != "code":
        raise RuntimeError("notebook cell 5 is not code")
    original = "".join(cell["source"])
    patched = patch_cell(original, args.profile)

    if args.check:
        if original != patched:
            print("notebook serving block is OUT OF DATE "
                  f"(profile={args.profile!r}); rerun without --check")
            return 1
        print(f"notebook serving block is up to date (profile={args.profile!r})")
        return 0

    if original == patched:
        print(f"notebook already up to date (profile={args.profile!r})")
        return 0
    cell["source"] = patched.splitlines(keepends=True)
    NOTEBOOK.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"patched {NOTEBOOK} with serving profile {args.profile!r}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
